package main

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/crispuscrew/zinc/creator/internal/compose"
	"github.com/crispuscrew/zinc/creator/internal/runner"
	"gopkg.in/yaml.v3"
)

func marshalProject(project compose.Project) ([]byte, error) {
	body, err := yaml.Marshal(project)
	if err != nil {
		return nil, err
	}
	header := "# Generated by zc compose export: a DESCRIPTION, not a replacement for Zinc.\n" +
		"# Ordered network rules and desktop/audio controls are not expressible here.\n"
	return append([]byte(header), body...), nil
}

func pinImage(reference string) (string, string, error) {
	trimmed := strings.TrimSpace(reference)
	switch {
	case trimmed == "":
		return "", "", errors.New("the service names no image")
	case strings.Contains(trimmed, "@sha256:"), strings.HasPrefix(trimmed, "localhost/"):
		return trimmed, "", nil
	}
	pinned, err := runner.Resolve(trimmed)
	if err != nil {
		return "", "", fmt.Errorf("image %q is not pinned and could not be resolved: %w; pin it with zc image resolve", trimmed, err)
	}
	return pinned, fmt.Sprintf("image %q was pinned to %s", trimmed, pinned), nil
}

func readProject(path string) (compose.Project, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return compose.Project{}, err
	}
	var project compose.Project
	decoder := yaml.NewDecoder(bytes.NewReader(data))
	if err := decoder.Decode(&project); err != nil {
		return project, fmt.Errorf("decode %s: %w", path, err)
	}
	var extra any
	if err := decoder.Decode(&extra); err != io.EOF {
		return project, fmt.Errorf("%s: expected one Compose document", path)
	}
	return project, nil
}

func printNotes(output io.Writer, label string, notes []string) {
	for _, note := range notes {
		fmt.Fprintf(output, "%s: %s\n", label, note)
	}
}
