package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/crispuscrew/zinc/creator/internal/backend"
	"github.com/crispuscrew/zinc/creator/internal/compose"
	"github.com/crispuscrew/zinc/creator/internal/runner"
)

const composeUsage = `usage:
  zc compose export <name|app.yaml> [-o compose.yaml]   describe an app as a compose file
  zc compose import <compose.yaml> [--service s] [--dry-run]   author apps from one

Neither direction is lossless, and both print what did not cross. Exporting drops
guarantees: a compose file cannot express the nftables egress lock-down, so the file
DESCRIBES an app rather than sandboxing it. Importing tightens: compose cannot say what a
service may reach, so an imported app arrives with no network at all.`

// splitLeadingArg takes the required positional off the front of an argv so the rest can be
// parsed as flags. Go's flag package stops at the first non-flag argument, so a command
// written `<thing> --flag` has to be split by hand or the flag is read as another
// positional and quietly does nothing.
func splitLeadingArg(argv []string) (string, []string, error) {
	if len(argv) < 1 || strings.HasPrefix(argv[0], "-") {
		return "", nil, fmt.Errorf("%s", composeUsage)
	}
	return argv[0], argv[1:], nil
}

// cmdCompose dispatches the compose subcommands (section 9.1).
func cmdCompose(svc backend.Service, argv []string) error {
	if len(argv) < 1 {
		return fmt.Errorf("%s", composeUsage)
	}
	switch argv[0] {
	case "export":
		return cmdComposeExport(svc, argv[1:])
	case "import":
		return cmdComposeImport(svc, argv[1:])
	default:
		return fmt.Errorf("unknown compose subcommand %q\n%s", argv[0], composeUsage)
	}
}

func cmdComposeExport(svc backend.Service, argv []string) error {
	// The app comes first and flags follow it, like `zc new`: Go's flag parser stops at the
	// first positional, so parsing the whole argv would silently ignore a trailing -o.
	name, flags, err := splitLeadingArg(argv)
	if err != nil {
		return err
	}
	fset := flag.NewFlagSet("compose export", flag.ContinueOnError)
	out := fset.String("o", "", "write to this file instead of stdout")
	if err := fset.Parse(flags); err != nil {
		return err
	}
	if fset.NArg() != 0 {
		return fmt.Errorf("unexpected argument %q (flags must follow the app name)", fset.Arg(0))
	}
	cfg, err := loadApp(svc, name)
	if err != nil {
		return err
	}
	project, notes, err := compose.FromApp(cfg)
	if err != nil {
		return err
	}
	data, err := marshalProject(project)
	if err != nil {
		return err
	}
	if *out == "" {
		if _, werr := os.Stdout.Write(data); werr != nil {
			return fmt.Errorf("write: %w", werr) // a truncated export must not look like a whole one
		}
	} else if err := os.WriteFile(*out, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", *out, err)
	} else {
		fmt.Printf("wrote %s\n", *out)
	}
	// stderr, so `zc compose export app > compose.yaml` still produces a clean file while
	// the reader is told what the file cannot say.
	printNotes(os.Stderr, "not represented", notes)
	return nil
}

// marshalProject encodes the project with a header saying what the file is. Someone will
// find this file later with no memory of where it came from, and the one thing they must
// not conclude is that running it reproduces the sandbox.
func marshalProject(project compose.Project) ([]byte, error) {
	body, err := yaml.Marshal(project)
	if err != nil {
		return nil, fmt.Errorf("encode: %w", err)
	}
	header := "# Generated by zc compose export - a DESCRIPTION of a Zinc app, not a\n" +
		"# replacement for it. Running this with podman-compose gives an ordinary\n" +
		"# container: the nftables egress lock-down Zinc applies to the app's network\n" +
		"# namespace before it starts is not expressible here. Launch it with `zcr run`.\n"
	return append([]byte(header), body...), nil
}

func cmdComposeImport(svc backend.Service, argv []string) error {
	path, flags, err := splitLeadingArg(argv)
	if err != nil {
		return err
	}
	fset := flag.NewFlagSet("compose import", flag.ContinueOnError)
	only := fset.String("service", "", "import just this one service from a multi-service file")
	dryRun := fset.Bool("dry-run", false, "print the app definitions instead of saving them")
	if err := fset.Parse(flags); err != nil {
		return err
	}
	if fset.NArg() != 0 {
		return fmt.Errorf("unexpected argument %q (flags must follow the file)", fset.Arg(0))
	}
	project, err := readProject(path)
	if err != nil {
		return err
	}
	apps := compose.ToApps(project)
	if *only != "" {
		apps = selectService(apps, *only)
		if len(apps) == 0 {
			return fmt.Errorf("no service %q in %s", *only, path)
		}
	}
	if len(apps) == 0 {
		return fmt.Errorf("%s defines no services", path)
	}

	// Every service is attempted, and the ones that cannot be made valid are reported at
	// the end rather than aborting the rest: a ten-service file with one unpinnable image
	// should import nine apps and say which one it could not.
	var failed []string
	for _, app := range apps {
		if err := importOne(svc, app, *dryRun); err != nil {
			fmt.Fprintf(os.Stderr, "zc: %s: %v\n", app.Config.AppNameID, err)
			failed = append(failed, app.Config.AppNameID)
		}
	}
	if len(failed) > 0 {
		return fmt.Errorf("%d of %d services could not be imported: %s",
			len(failed), len(apps), strings.Join(failed, ", "))
	}
	return nil
}

// importOne pins the service's image, then saves it (which validates) or prints it.
func importOne(svc backend.Service, app compose.App, dryRun bool) error {
	cfg := app.Config
	notes := app.Notes
	if pinned, pinNote, err := pinImage(cfg.ImageMeta.Image); err != nil {
		return err
	} else {
		cfg.ImageMeta.Image = pinned
		if pinNote != "" {
			notes = append(notes, pinNote)
		}
	}

	if dryRun {
		data, err := svc.Marshal(cfg)
		if err != nil {
			return err
		}
		fmt.Printf("# --- %s ---\n%s\n", cfg.AppNameID, data)
		printNotes(os.Stdout, "note", notes)
		return nil
	}
	if svc.Exists(cfg.AppNameID) {
		return fmt.Errorf("already exists at %s (rename it, or import with --dry-run and merge by hand)", svc.Path(cfg.AppNameID))
	}
	if err := svc.Save(cfg); err != nil { // validates: image policy, schema, network shapes
		return err
	}
	fmt.Printf("imported %s → %s\n", cfg.AppNameID, svc.Path(cfg.AppNameID))
	printNotes(os.Stdout, "note", notes)
	return nil
}

// pinImage resolves a mutable tag to its digest, because Zinc runs what was authorised and
// a compose file names an image that can change under it. This is the one part of the
// import that needs the network and the runner, so its failure is a clear message about
// what to do rather than a silently unpinned app - which would not save anyway, since
// validation refuses one.
func pinImage(ref string) (pinned, note string, err error) {
	trimmed := strings.TrimSpace(ref)
	switch {
	case trimmed == "":
		return "", "", errors.New("the service names no image")
	case strings.Contains(trimmed, "@sha256:"), strings.HasPrefix(trimmed, "localhost/"):
		return trimmed, "", nil
	}
	resolved, rerr := runner.Resolve(trimmed)
	if rerr != nil {
		return "", "", fmt.Errorf("image %q is not digest-pinned and could not be resolved (%v).\n"+
			"        Zinc runs what was authorised, so a mutable tag is refused. Pin it with:\n"+
			"          zc image resolve %s", trimmed, rerr, trimmed)
	}
	return resolved, fmt.Sprintf("image %q was pinned to %s - the tag could move, the digest cannot", trimmed, resolved), nil
}

// readProject decodes a compose file. Unknown keys are NOT rejected here, unlike an app
// file: a compose file is someone else's, written for a tool with a far larger vocabulary,
// and refusing it over a `build:` key this importer has no use for would reject most real
// files. What was ignored and mattered comes back as a note.
func readProject(path string) (compose.Project, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return compose.Project{}, fmt.Errorf("read %s: %w", path, err)
	}
	var project compose.Project
	if err := yaml.NewDecoder(bytes.NewReader(data)).Decode(&project); err != nil {
		if errors.Is(err, io.EOF) {
			return compose.Project{}, fmt.Errorf("%s: empty file", path)
		}
		return compose.Project{}, fmt.Errorf("decode %s: %w", path, err)
	}
	return project, nil
}

// selectService narrows a multi-service import to one, matched on either the compose key as
// written in the file or the app name it was coerced to. The key is what the user is reading
// when they choose; requiring the coerced name would mean guessing what the coercion did.
func selectService(apps []compose.App, want string) []compose.App {
	for _, app := range apps {
		if app.Service == want || app.Config.AppNameID == want {
			return []compose.App{app}
		}
	}
	return nil
}

func printNotes(out io.Writer, label string, notes []string) {
	for _, note := range notes {
		fmt.Fprintf(out, "%s: %s\n", label, note)
	}
}
