package disk

import "strings"

// windowsSetup renders zinc-setup.cmd, the one thing a Windows guest can be handed that it
// will actually run. Everything Zinc can do for such a guest stops at the machine: the
// drivers that make the machine worth having live on the virtio-win disc and can only be
// staged from inside Windows, by a user with an administrator token. So the script goes to
// the guest rather than the instructions going to the reader.
//
// It stages all three drivers, not just the display one. viostor is the reason: switching an
// app to Devices: Virtio without it already installed leaves Windows unable to see its own
// boot disk (INACCESSIBLE_BOOT_DEVICE), and staging a driver for hardware that is not
// present yet is exactly what pnputil's driver store is for. Nothing here changes the
// running machine, so the script is safe to run twice and safe to run early.
//
// Written as a .cmd rather than PowerShell because a .cmd runs on a double-click with no
// execution policy to argue with, and because this has to work on a guest whose network has
// never come up.
func windowsSetup() string {
	lines := []string{
		`@echo off`,
		`rem Zinc guest setup: stage the virtio drivers this machine can use.`,
		`rem Generated by zvr. Safe to run more than once; nothing here changes the`,
		`rem hardware the guest is running on right now.`,
		`title Zinc guest setup`,
		``,
		`rem pnputil needs an administrator token. A double-clicked script does not have`,
		`rem one, so it re-launches itself elevated rather than failing at the first driver.`,
		`net session >nul 2>&1`,
		`if not errorlevel 1 goto elevated`,
		`powershell -NoProfile -Command "Start-Process -FilePath '%~f0' -Verb RunAs" >nul 2>&1`,
		`if errorlevel 1 (`,
		`    echo Could not elevate. Right-click this file and pick "Run as administrator".`,
		`    pause`,
		`)`,
		`exit /b`,
		``,
		`:elevated`,
		`rem The driver disc's letter depends on what else is attached, so find it by`,
		`rem looking for a file only it has. w11 first, w10 for an older virtio-win build.`,
		`set "DISC="`,
		`set "REL="`,
		`for %%D in (D E F G H I J K L M N O P Q R S T U V W X Y Z) do (`,
		`    if exist "%%D:\viogpudo\w11\amd64\viogpudo.inf" (`,
		`        set "DISC=%%D:"`,
		`        set "REL=w11"`,
		`    )`,
		`)`,
		`if not defined DISC for %%D in (D E F G H I J K L M N O P Q R S T U V W X Y Z) do (`,
		`    if exist "%%D:\viogpudo\w10\amd64\viogpudo.inf" (`,
		`        set "DISC=%%D:"`,
		`        set "REL=w10"`,
		`    )`,
		`)`,
		`if not defined DISC (`,
		`    echo The virtio-win disc is not attached to this guest.`,
		`    echo Re-author the app with:  --media ...\virtio-win.iso`,
		`    pause`,
		`    exit /b 1`,
		`)`,
		`echo Using the driver disc at %DISC% (%REL%^)`,
		`echo.`,
		``,
		`set FAILED=0`,
		`call :stage "%DISC%\viogpudo\%REL%\amd64\viogpudo.inf" "display"`,
		`call :stage "%DISC%\viostor\%REL%\amd64\viostor.inf" "disk"`,
		`call :stage "%DISC%\NetKVM\%REL%\amd64\netkvm.inf" "network"`,
		``,
		`echo.`,
		`if not "%FAILED%"=="0" (`,
		`    echo %FAILED% driver(s^) did not install. Nothing has been changed.`,
		`    pause`,
		`    exit /b 1`,
		`)`,
		`echo All three drivers are staged.`,
		`echo.`,
		`echo Next: shut this guest down, then re-author the app with`,
		`echo   --display Window          a driven display: any size, resizes with the window`,
		`echo   --devices Virtio          a faster disk and network`,
		`echo and drop --resolution, which only exists for a guest that cannot resize itself.`,
		`pause`,
		`exit /b 0`,
		``,
		`:stage`,
		`if not exist %1 (`,
		`    echo   %~2: not on this disc, skipped`,
		`    goto :eof`,
		`)`,
		`echo   %~2 driver ...`,
		`pnputil /add-driver %1 /install`,
		`if errorlevel 1 set /a FAILED+=1`,
		`goto :eof`,
	}
	// CRLF: a .cmd with bare newlines is read by cmd.exe one byte at a time and misparses
	// the moment a line matters, which is every line here.
	return strings.Join(lines, "\r\n") + "\r\n"
}
