SchemaVersion: 4
Type: ZincContainer
AppNameID: producer
LauncherMeta:
  Description: provisioned app network - allow the consumer on port 5432 only
ImageMeta:
  Image: localhost/zinc/e2e-app:local
StartConditions:
  Entrypoint: /listen.sh
NetworkMeta:
  Interfaces:
    - ID: link
  RulesByPriority:
    - From: {Type: App, AppNameID: consumer, Interface: link}
      To:
        Type: Self
        Interface: link
        Filter: {Ports: [5432]}
      Protocols: [TCP]
